#!/usr/bin/env bash
# Install nginx on a server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo rm /var/www/html/index.html
sudo bash -c "echo 'Holberton School' > /var/www/html/index.html"
