#!/usr/bin/env bash
# Bash (init) script that manages manage_my_process script ({start|stop|restart})
if [ $# -eq 0 ]
then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

case $1 in
  start)
    ./manage_my_process &
    if [ $? -eq 0 ]
    then
      echo "manage_my_process started"
    fi
    ;;
  stop)
    export pr="$(< /var/run/my_process.pid)"
    kill -15 "$pr"
    if [ $? -eq 0 ]
    then
      echo "manage_my_process stopped"
    fi
    ;;
  restart)
    export pro="$(< /var/run/my_process.pid)"
    kill -15 "$pro"
    while kill -0 "$pro"
    do 
      sleep 1
    done 2> /dev/null
    if [ $? -eq 0 ]
    then
      ./manage_my_process &
      if [ $? -eq 0 ]
      then
        echo "manage_my_process restarted"
      fi
    fi
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac
