#!/usr/bin/env bash
# Script that displays the visitor IP along with the HTTP status code from the Apache log file. In top rank.
awk '{ printf "%s %s\n", $1, $9}' apache-access.log | sort | uniq -c | sort -hr
