#!/usr/bin/env bash
# Script that displays Holberton School 10 times, and Hi between 9 and 10..
export i=1
while [[ "$i" -le "10" ]]
do
  echo "Holberton School"
  if [[ "$i" -eq "9" ]]
  then
    echo "Hi"
  fi
  let i=i+1
done
