#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes.
export i=0
export j=1
while [[ "$i" -le "23" ]]
do
  echo "Hour: $i"
  let j=1
  while [[ "$j" -le "59" ]]
  do
    echo $j
    let j=j+1
  done
  let i=i+1
done
