#!/bin/bash
# Configures the firewall by ufw to allow only incoming TCP 22, 80, 443 ports
sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp
